run:
  tests: true
  skip-dirs-use-default: false
  skip-dirs:
    - grpc/client/rest/*
    - bundle/*
    - generated/*
    - otelginmetrics/*
  timeout: 15m
  skip-files:
    - '.*\.abigen\.go$'
    - '.*\.metadata\.go$'
    - '.*\.pb\.go$'
    - '.*_gen.go$'

linters-settings:
  gofmt:
    simplify: true
  govet:
    check-shadowing: false
  misspell:
    locale: US
  gocritic:
    disabled-checks:
      - appendAssign
  cyclop:
    max-complexity: 15

linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - gosimple
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - gosec
    - cyclop
    - revive
    - stylecheck
    - gocritic
    - misspell
    - gocyclo
    - dupl
    - wrapcheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - revive
        - stylecheck
        - dupl
    - path: export_test\.go
      linters:
        - wrapcheck
      text: 'should not use dot imports'
    - path: contracts/
      linters:
        - revive
      text: 'and that stutters; consider calling this'
    - path: ethergo/example/*
      linters:
        - wrapcheck
    - path: testutil/*
      linters:
        - wrapcheck
    - path: ethergo/*
      linters:
        - staticcheck
      text: 'SA1019'
    - path: \.resolvers\.go
      linters:
        - cyclop
    - path: signoz/*
      linters:
        - mnd
        - stylecheck
    - path: example/*
      linters:
        - revive
        - cyclop
        - forcetypeassert
        - staticcheck
        - wrapcheck
  exclude-use-default: false
  new-from-rev: 9fe0f033b73acf6b8240f0a832c4b4d21e68181b
